source 'http://gemcutter.org'

gem "rails",          "~> 3.0.0"
gem "haml",           "~> 3.0.23"
gem "bluecloth",      "~> 2.0.7"
gem "sqlite3-ruby",   "~> 1.3.1",   :require => "sqlite3"
gem "will_paginate",  "~> 3.0.beta"
gem "paperclip",      "~> 2.3.5"
